CREATE TABLE schedules (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    enterprise_id BIGINT NOT NULL COMMENT 'Tenant ID',
    construction_site_id BIGINT NOT NULL COMMENT 'References construction_sites',
    creator_worker_id BIGINT NOT NULL COMMENT 'References personnel',
    creator_vendor_id BIGINT NOT NULL COMMENT 'References vendors',
    title VARCHAR(500) NOT NULL COMMENT 'Schedule title required',
    category_id BIGINT NOT NULL COMMENT 'References schedule_categories',
    is_all_day BOOLEAN DEFAULT FALSE COMMENT 'All day event flag',
    start_datetime TIMESTAMP NOT NULL COMMENT 'Start date time required',
    end_datetime TIMESTAMP NOT NULL COMMENT 'End date time required',
    is_public BOOLEAN DEFAULT FALSE COMMENT 'Public to all in construction site',
    alert_type VARCHAR(50) COMMENT 'Alert reminder type',
    alert_custom_minutes INT COMMENT 'Custom alert minutes',
    content TEXT COMMENT 'Detailed content',
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME NULL COMMENT 'Soft delete',
    FOREIGN KEY (construction_site_id) REFERENCES construction_sites(id) ON DELETE RESTRICT,
    FOREIGN KEY (creator_worker_id) REFERENCES personnel(id) ON DELETE RESTRICT,
    FOREIGN KEY (creator_vendor_id) REFERENCES vendors(id) ON DELETE RESTRICT,
    FOREIGN KEY (category_id) REFERENCES schedule_categories(id) ON DELETE RESTRICT,
    INDEX idx_enterprise_site (enterprise_id, construction_site_id),
    INDEX idx_creator_worker (creator_worker_id),
    INDEX idx_creator_vendor (creator_vendor_id),
    INDEX idx_category (category_id),
    INDEX idx_datetime (start_datetime, end_datetime),
    INDEX idx_deleted (deleted_at)
);