CREATE TABLE schedules (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    enterprise_id VARCHAR(255) NOT NULL COMMENT 'Tenant ID from JWT',
    construction_site_id VARCHAR(255) NOT NULL COMMENT 'From Forxai API',
    creator_worker_id VARCHAR(255) NOT NULL COMMENT 'Creator Worker ID from JWT',
    creator_vendor_id VARCHAR(255) NOT NULL COMMENT 'Creator Vendor ID from JWT',
    title VARCHAR(500) NOT NULL COMMENT 'Schedule title required',
    category_id BIGINT NOT NULL COMMENT 'Category ID',
    is_all_day BOOLEAN DEFAULT FALSE COMMENT 'All day event flag',
    start_datetime TIMESTAMP NOT NULL COMMENT 'Start date time required',
    end_datetime TIMESTAMP NOT NULL COMMENT 'End date time required',
    is_public BOOLEAN DEFAULT FALSE COMMENT 'Public to all in construction site',
    alert_type VARCHAR(50) COMMENT 'Alert reminder type',
    alert_custom_minutes INT COMMENT 'Custom alert minutes',
    content TEXT COMMENT 'Detailed content',
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME NULL COMMENT 'Soft delete',
    FOREIGN KEY (category_id) REFERENCES schedule_categories(id),
    INDEX idx_enterprise_site (enterprise_id, construction_site_id),
    INDEX idx_creator (creator_worker_id),
    INDEX idx_datetime (start_datetime, end_datetime),
    INDEX idx_deleted (deleted_at)
);